### ISSUE TITLE
Ошибка в 4.27

### ISSUE THREAD

**Issue by cppgod17** [rionix/LocalizationUE4#2]
При попытке открыть game.manifest в 4.27 версии двигла, выдает ошибку invalid version

**Comment by Rasta42** [comment]
Тоже появилась такая ошибка в 4.27 однако до этого я уже открывал game.manifest 4.27 и загружал локализацию.

**Comment by maltsevda** [comment]
Можно получить файлы вызывающие ошибку? Прям всю папку содержащую *.manifest. Я попробую найти ошибку.

**Comment by Rasta42** [comment]
Даже если убрать все StringTable из сборки для локализации он отказывается открывать с той же ошибкой

https://drive.google.com/file/d/1Xqsb9-A7wRronUVAK2A6XCa28XWEALnm/view?usp=sharing

**Comment by maltsevda** [comment]
Выложил новый релиз 1.7.0. Вроде бы ошибку поправил. Проверяйте, если все окей, то закрываем тему.

**Comment by Rasta42** [comment]
Заработало! Спасибо вам огромное за прогу и за помощь) Очень удобная штука) Можно вам куда нибудь задонатить?)

**Comment by maltsevda** [comment]
Донатить не надо, но большое спасибо за поддержку! Пользуйтесь на здоровье. :)
